version: '3.1'

services:
  db:
    container_name: snowtricks
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 #SMTP
      - 8025:8025 #boite mail
volumes:
  my-db: